name: Prac Gegner

# Definiert, wann der Workflow ausgelöst wird (jede Stunde)
on:
  schedule:
    - cron: "0 0 * * *"  # Jede volle Stunde
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: 
      name : app

    env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        GOOGLE_KALENDER_ID: ${{ secrets.GOOGLE_KALENDER_ID }}
        NOTION_PRAC_LIST: ${{ secrets.NOTION_PRAC_LIST }}
        NOTION_ENEMY_LIST: ${{ secrets.NOTION_ENEMY_LIST }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{secrets.GOOGLE_SERVICE_ACCOUNT_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client notion-client python-dotenv
          
      - name: Run script
        run: |
          python ./PracGegner.py
